#!/bin/bash
sudo /bin/snmptrap \
  -v3 -d \
  -u AUTHENTICv3 \
  -l authPriv \
  -a SHA \
  -A Test1234! \
  -x AES \
  -X Test1234! \
  -e 0x8000047304434b4d39383736353433323130 \
  192.168.9.202 \
  6 \
  .1.3.6.1.2.1.1331.11.1.152.0 \
  .1.3.6.1.2.1.1331.11.1.152.1 \
  s "MACHINE:saf-prdautapp53.saf-prd.icc.corp; EVENT:BATCH_SUCCESS_WITH_ERRORS B0010; CATEGORY:SYSTEM-WARNING System Warning; TIME:$; PROCESS:BatchImportProcess-BATCH; IAP:; SHORTDESC:Batch Process [valueSetItem.batch.import] Completed with errors. Processed 608 records. Errors 3 records; LONGDESC:;"
